# Generated by Django 5.1.2 on 2024-10-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('bought_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bought_date', models.DateField()),
                ('market_price_today', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('low_stock_alert_threshold', models.IntegerField(default=10)),
            ],
        ),
    ]
