# Generated by Django 5.1.2 on 2024-10-24 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'permissions': [('can_view_staff', 'Can view staff'), ('can_change_staff', 'Can change staff')]},
        ),
    ]
