# Generated by Django 5.1.2 on 2024-10-28 12:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staff_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='scheduled_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
